<x-app-layout>
 <x-Home.banner></x-Home.banner>
 <x-Home.features></x-Home.features>
 <x-Home.categories></x-Home.categories>
 <x-Home.newProducts></x-Home.newProducts>
 <x-Home.ads></x-Home.ads>
 <x-Home.products></x-Home.products>
 <x-Home.footer></x-Home.footer>
</x-app-layout>
